//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvjeraModela
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.ZaposleniciNaProjektus = new HashSet<ZaposleniciNaProjektu>();
        }
    
        public int IDRezervacija { get; set; }
        public Nullable<int> IDSmjestaj { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
    
        public virtual Smjestaj Smjestaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZaposleniciNaProjektu> ZaposleniciNaProjektus { get; set; }
    }
}
